#!/bin/sh

diy=185x
float=150x
builds_folder="./png/builds"
crop_mods=550x795+1320+175

# Everything inside a table doesn't need to be resized.
find "$builds_folder"/01-Personal/ -name "*.png" -exec mogrify -crop "$crop_mods" -format jpg '{}' \;
find "$builds_folder"/02-Greenbeard/ -name "*.png" ! -name "Perks*" ! -name 01.Armor_green_build.png -exec mogrify -crop 1820x795+50+175 -format jpg '{}' \;
find "$builds_folder"/02-Greenbeard/ -name 01.Armor_green_build.png -exec mogrify -crop "$crop_mods" -resize "$float" -format jpg '{}' \;
find "$builds_folder"/02-Greenbeard/06-Perks/ -name "*.png" -exec convert {} {}.jpg \;
find "$builds_folder"/03-DIY/ -name "*.png" -exec mogrify -crop "$crop_mods" -resize "$diy" -format jpg '{}' \;
find ./png/mod_trees/ -name "*.png" -exec mogrify -crop "$crop_mods" -format jpg '{}' \;
find . -name Fancy.png -exec mogrify -crop 450x700+735+225 -resize "$float" -format jpg {} \;

if [ ! -d jpg ]; then
	mkdir jpg
fi

find ./png/ -name "*.jpg" -exec cp {} ./jpg/ --parents \;
find ./png/ -name "*.jpg" -exec rm {} +

# mogrify -resize 24x12 -format jpeg original/icons/index/DIY/weapons/*.webp
# mogrify -resize 12x12 -format jpeg original/icons/index/DIY/classes/*.webp
# mogrify -resize 12x12 -format jpeg original/icons/index/greenbeard/*.webp
# mogrify -resize 12x12 -format jpeg original/icons/index/personal/*.webp
# mogrify -resize 16x16 -format jpeg original/icons/missions/*.webp
# mogrify -resize 16x16 -format jpeg original/icons/warnings/*.webp
