#!/bin/sh

diy=185x
float=150x
crop_mods=550x795+1320+175
dest_jpg=../jpg/"{.}".jpg
dest_png=../png/"{.}".png
png_exclude=png:exclude-chunks=tIME,date

fd . "01-Personal/" -e png -E "*Perks*" --base-directory builds/png -x convert {} -crop "$crop_mods" "$dest_jpg" \;
fd "Perks" "01-Personal/" --base-directory builds/png -x convert {} -crop 57x291+470+180 "$dest_jpg" \;
fd . "02-Greenbeard/" -e png -E "Perks*" -E 01.Armor_green_build.png --base-directory builds/png -x convert {} -crop 1820x795+50+175 "$dest_jpg" \;
fd 01.Armor_green_build.png --base-directory builds/png -x convert {} -crop "$crop_mods" -resize "$float" "$dest_jpg" \;
fd . "02-Greenbeard/06-Perks/" -e png --base-directory builds/png -x convert {} "$dest_jpg" \;
fd . "03-DIY/" -e png -E "*Perk*" --base-directory builds/png -x convert {} -crop "$crop_mods" -resize "$diy" "$dest_jpg" \;
fd -e png --base-directory mod_trees/png -x convert {} -crop "$crop_mods" "$dest_jpg" \;
fd Fancy.png --base-directory misc/png -x convert {} -crop 450x700+735+225 -resize "$float" "$dest_jpg" \;
fd -e webp --base-directory icons/missions/webp -x convert -define "$png_exclude" -resize 16 {} "$dest_png" \;
fd -e webp --base-directory icons/warnings/webp -x convert -define "$png_exclude" -resize 16 {} "$dest_png" \;
fd -e webp --base-directory icons/index/greenbeard/webp -x convert -define "$png_exclude" -resize x12 {} "$dest_png" \;
fd -e webp --base-directory icons/index/personal/webp -x convert -define "$png_exclude" -resize 12 {} "$dest_png" \;
fd -e webp --base-directory icons/index/DIY/classes/webp -x convert -define "$png_exclude" -resize 12 {} "$dest_png" \;
fd -e webp --base-directory icons/index/DIY/weapons/webp -x convert -define "$png_exclude" -resize x12 {} "$dest_png" \;
